apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: prod-sc
spec:
  selector:
    app: elasticsearch
  ports:
    - port: 9200
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: prod-sc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
          ports:
            - containerPort: 9200
          env:
            - name: discovery.type
              value: single-node
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
          volumeMounts:
            - name: esdata
              mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: esdata
          emptyDir: {}
