apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-refresh-servico-reunidas
  namespace: prod-sc
spec:
  # Every day at 04:00
  schedule: "0 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: refresh-servico-reunidas
              image: curlimages/curl:8.6.0
              imagePullPolicy: IfNotPresent
              args:
                - -X
                - POST
                - http://api-pos-gateway-service/reunidas/linhas/refresh

